### PR TITLE
Fix lower bound on `base`

### PR DESCRIPTION
**Pull request by hvr**
Since this fails to compile with GHC 7.8.4/base-4.7 (and Travis doesn't appear to be testing it either):

```
Configuring component lib from IPv6Addr-0.6.3
Preprocessing library IPv6Addr-0.6.3...
[1 of 4] Compiling Text.IPv6Addr.Types ( Text/IPv6Addr/Types.hs, /tmp/matrix-worker/1482774573/dist-newstyle/build/x86_64-linux/ghc-7.8.4/IPv6Addr-0.6.3/build/Text/IPv6Addr/Types.o )
[2 of 4] Compiling Text.IPv6Addr.Internal ( Text/IPv6Addr/Internal.hs, /tmp/matrix-worker/1482774573/dist-newstyle/build/x86_64-linux/ghc-7.8.4/IPv6Addr-0.6.3/build/Text/IPv6Addr/Internal.o )

Text/IPv6Addr/Internal.hs:256:34:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid),
      ‘<|>’ (imported from Control.Applicative),
      ‘<?>’ (imported from Data.Attoparsec.Text)

Text/IPv6Addr/Internal.hs:262:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:263:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:264:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:265:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:266:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:283:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:285:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:287:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)
```

### CODE REVIEW

**Comment by hvr** [comment]
sorry... ignore this, I wanted to file a 2nd PR against `ip6addr` and got confused (and it turns out that `ip6addr` is actually fine after fixing up the metadata for `IPv6Addr` on hackage...) :-)

**Comment by MichelBoucey** [comment]
I have tested and discard 7.8.4 build but I haven't seen that base lower bound was bad... thank you. I am gonna do the same change on my other packages.
