### PR TITLE
Fix lower bound on `base`

### PR DESCRIPTION
**Pull request by hvr**
As this currently doesn't build with GHC 7.8.4 yet (and the Travis config doesn't appear to test against GHC 7.8.4 either)

```
Configuring component lib from IPv6Addr-0.6.3
Preprocessing library IPv6Addr-0.6.3...
[1 of 4] Compiling Text.IPv6Addr.Types ( Text/IPv6Addr/Types.hs, /tmp/matrix-worker/1482774573/dist-newstyle/build/x86_64-linux/ghc-7.8.4/IPv6Addr-0.6.3/build/Text/IPv6Addr/Types.o )
[2 of 4] Compiling Text.IPv6Addr.Internal ( Text/IPv6Addr/Internal.hs, /tmp/matrix-worker/1482774573/dist-newstyle/build/x86_64-linux/ghc-7.8.4/IPv6Addr-0.6.3/build/Text/IPv6Addr/Internal.o )

Text/IPv6Addr/Internal.hs:256:34:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid),
      ‘<|>’ (imported from Control.Applicative),
      ‘<?>’ (imported from Data.Attoparsec.Text)

Text/IPv6Addr/Internal.hs:262:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:263:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:264:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:265:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:266:26:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:283:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:285:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)

Text/IPv6Addr/Internal.hs:287:20:
    Not in scope: ‘<*’
    Perhaps you meant one of these:
      ‘<>’ (imported from Data.Monoid), ‘*’ (imported from Prelude),
      ‘**’ (imported from Prelude)
```

### CODE REVIEW

**Comment by hvr** [comment]
Fyi, I've fixed up the meta-data for affected versions (and also backported `0.6.3`'s constraints):

 - https://hackage.haskell.org/package/IPv6Addr-0.6.3/revisions/
 - https://hackage.haskell.org/package/IPv6Addr-0.6.2.0/revisions/
 - https://hackage.haskell.org/package/IPv6Addr-0.6.1.0/revisions/

This had the benefit of fixing `ip6addr`'s compilation as now the solver picks the most recent `IPv6Addr` release which still worked with GHC 7.8.4
